// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2021-11-01 22:17:02.4774775 +0800 CST m=+0.083775401

package docs

import (
	"bytes"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "swagger": "2.0",
    "info": {
        "description": "回迁平台",
        "title": "relocate",
        "contact": {},
        "license": {},
        "version": "1.0"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/accounting": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "核算"
                ],
                "summary": "根据合同号、被拆迁人模糊查询分页查询核算列表（筛选功能）(管理员)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "搜索关键字(合同号、被拆迁人)",
                        "name": "filterName",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页面大小",
                        "name": "pageSize",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/app.Response"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "核算"
                ],
                "summary": "根据合同号核算",
                "parameters": [
                    {
                        "description": "核算信息",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/AddAccountingBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/app.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/accounting/export": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "核算"
                ],
                "summary": "导出核算表(管理员)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "搜索关键字(合同号、被拆迁人)",
                        "name": "filterName",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/app.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/get": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理员"
                ],
                "summary": "获取所有的管理员账号和姓名",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/app.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/login": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理员"
                ],
                "summary": "管理员登录账号admin密码123456",
                "parameters": [
                    {
                        "description": "登录信息",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/AdminLoginBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/app.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/update": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理员"
                ],
                "summary": "修改密码(账号，旧密码，新密码)",
                "parameters": [
                    {
                        "description": "手机号码，旧密码，新密码",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/AdminUpdateBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/app.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/config/declaration/active/get": {
            "get": {
                "description": "查询摇珠不中是否计入总数状态(0：表示不计入总数，1：表示计入总数)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "全局配置"
                ],
                "summary": "查询摇珠不中是否计入总数状态(0：表示不计入总数，1：表示计入总数)",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/app.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/config/declaration/active/setting": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "后台管理员设置摇珠不中是否计入总数",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "全局配置"
                ],
                "summary": "设置摇珠不中是否计入总数",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "状态 --0：申报不计入总数；1：申报计入总数",
                        "name": "state",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/app.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/config/huxing/groupingOptional/get": {
            "get": {
                "description": "查询分组总可选套数",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "全局配置"
                ],
                "summary": "查询分组总可选套数",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/app.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/config/huxing/groupingOptional/setting": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "后台管理员设置分组总可选套数",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "全局配置"
                ],
                "summary": "设置分组总可选套数",
                "parameters": [
                    {
                        "description": "配置信息",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/GroupingOptionalBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/app.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/config/rounds/get": {
            "get": {
                "description": "获取当前轮次",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "全局配置"
                ],
                "summary": "获取当前轮次",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/app.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/config/rounds/setting": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "后台管理员设置当前轮次",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "全局配置"
                ],
                "summary": "设置当前轮次",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "分期id值",
                        "name": "rounds",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/app.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/config/staging/get": {
            "get": {
                "description": "获取当前分期",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "全局配置"
                ],
                "summary": "获取当前分期",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/app.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/config/staging/setting": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "后台管理员设置当前分期",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "全局配置"
                ],
                "summary": "设置当前分期",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "分期id值",
                        "name": "stagingId",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/app.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/contract/addCardNumber": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "根据合同号增加身份证",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "合同单"
                ],
                "summary": "根据合同号增加身份证",
                "parameters": [
                    {
                        "description": "证件号",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/AddCardNumberBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/app.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/contract/new": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "根据分期期数新增合同单",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "合同单"
                ],
                "summary": "根据分期期数新增合同单",
                "parameters": [
                    {
                        "description": "合同信息",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/api.AddContractBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/app.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/contract/supplement": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "合同单"
                ],
                "summary": "补充导入指标安置面积、计算临迁费面积",
                "parameters": [
                    {
                        "type": "file",
                        "description": "拆迁人Excel原始数据",
                        "name": "excel",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/app.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/contract/updateHouseWriteOff": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "传入一个合同号数组和一个要设置的房屋注销选项，批量修改",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "合同单"
                ],
                "summary": "根据合同号确定每一项合同是否完成房屋注销的选项",
                "parameters": [
                    {
                        "description": "根据合同号批量修改是否注销",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/UpdateHouseWriteOffBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/app.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/declaration/add": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "根据合同号新增申报(操作人 管理员姓名、登录人姓名)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "申报单"
                ],
                "summary": "根据合同号新增申报(操作人 管理员姓名、登录人姓名)",
                "parameters": [
                    {
                        "description": "申报信息",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/api.AddDeclarationBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/app.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/declaration/addNew": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "根据合同号新增申报(操作人 管理员姓名、登录人姓名)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "申报单"
                ],
                "summary": "根据合同号新增申报(操作人 管理员姓名、登录人姓名)",
                "parameters": [
                    {
                        "description": "申报信息",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/api.AddDeclarationBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/app.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/declaration/getAdminName": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "申报表打印管理员姓名(管理员)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "申报单"
                ],
                "summary": "申报表打印管理员姓名(管理员)",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/app.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/declaration/getAll": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "获取所有的申报表列表",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "申报单"
                ],
                "summary": "获取所有的申报表列表",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/app.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/declaration/printing": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "申报单"
                ],
                "summary": "打印申报表(管理员)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "申报表ID",
                        "name": "declaration_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/app.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/declaration/updateDeclarationStatus": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "根据申报表ID更改申报状态(管理员)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "申报单"
                ],
                "summary": "根据申报表ID更改申报状态(管理员)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "申报ID（必须）",
                        "name": "declaration_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "申报表申报状态（必须）-- 0：表示进行中；1：表示已确定",
                        "name": "status",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/app.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/huxing/get/optional": {
            "get": {
                "description": "获取户型（可选\u003e0以上的）",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "户型"
                ],
                "summary": "获取户型（可选\u003e0以上的）",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "分期期数",
                        "name": "staging_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/app.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/information/delete": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "后台管理员删除资讯",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "资讯"
                ],
                "summary": "删除资讯",
                "parameters": [
                    {
                        "description": "资讯id",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/DeleteInformationBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/app.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/information/get": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "分页获取资讯列表",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "资讯"
                ],
                "summary": "分页获取资讯列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页面大小",
                        "name": "pageSize",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/app.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/information/new": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "后台管理员新增资讯",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "资讯"
                ],
                "summary": "新增资讯",
                "parameters": [
                    {
                        "description": "资讯标题（必须），内容（必须），图片(base64字符串),图片后缀(例如.jpg)",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/NewInformationBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/app.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/information/updateStatus": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "后台管理员修改资讯状态",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "资讯"
                ],
                "summary": "修改资讯状态",
                "parameters": [
                    {
                        "description": "资讯id(必须),status状态int（0待发布中,1已发布）",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/UpdateInformationStatusBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/app.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/information/upload": {
            "post": {
                "description": "上传图片，返回图片链接",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "资讯"
                ],
                "summary": "上传图片，返回图片链接",
                "parameters": [
                    {
                        "description": "上传图片的信息",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/UploadImageBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/app.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/result/export": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "根据分期期数（必须）导出摇珠表列表(管理员)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "公示"
                ],
                "summary": "导出摇珠表列表(管理员)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "分期期数（必须）",
                        "name": "stagingId",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/app.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/result/get": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "根据分期期数（必须）、户型、身份证号、合同号、手机号 模糊查询分页查询摇珠结果列表（筛选功能）(管理员)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "公示"
                ],
                "summary": "根据分期期数（必须）、户型、公示状态、身份证号、合同号、手机号 模糊查询分页查询摇珠结果列表（筛选功能）(管理员)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "分期期数（必须）",
                        "name": "stagingId",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "搜索关键字(姓名、身份证号、合同号、手机号)",
                        "name": "filterName",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "户型id",
                        "name": "huxing_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "是否公示  0表示公示状态为false的数据，1表示公示状态为true的数据，不选则显示所有",
                        "name": "公示状态",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页面大小",
                        "name": "pageSize",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/app.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/staging/getCount": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "分页根据分期id查询分期信息(包括每个分期合同单的数量)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "分期"
                ],
                "summary": "分页查询分期信息(包括每个分期合同单的数量)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页面大小",
                        "name": "pageSize",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/app.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/staging/import": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "后台管理员根据分期期数导入合同单原始数据",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "分期"
                ],
                "summary": "导入合同单原始数据",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "分期期数",
                        "name": "stagingId",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "拆迁人Excel原始数据",
                        "name": "excel",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/app.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/user/findMyself": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "用户通过手机查看自己的身份信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户通过手机号查看身份信息",
                        "name": "phone",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/app.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/user/get": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "获取验证码(注册)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "手机号码",
                        "name": "phone_number",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/app.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/user/register": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "注册(通过手机号码+密码注册+验证码)",
                "parameters": [
                    {
                        "description": "注册信息",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/UserRegisterBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/app.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/user/validator": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "用户进行身份核验",
                "parameters": [
                    {
                        "description": "用户身份信息",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/UserInfoBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/app.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.AddContractBody": {
            "type": "object",
            "required": [
                "card_number",
                "contract_no",
                "date_of_delivery",
                "date_of_signing",
                "house_number",
                "old_address",
                "peoples",
                "signatory",
                "social_category",
                "staging_id"
            ],
            "properties": {
                "can_declare": {
                    "description": "是否可申报(不写默认不可，1为可)",
                    "type": "boolean"
                },
                "card_number": {
                    "description": "身份证号码(必须，可能有多个)",
                    "type": "string"
                },
                "change_method": {
                    "description": "变更方式 \t//受托人关系",
                    "type": "string"
                },
                "collective_land_property_certificate": {
                    "description": "集体土地房产证字",
                    "type": "string"
                },
                "contract_no": {
                    "description": "合同号(必须)",
                    "type": "string"
                },
                "date_of_delivery": {
                    "description": "交楼日期(必须)",
                    "type": "string"
                },
                "date_of_signing": {
                    "description": "签署协议日期(必须)",
                    "type": "string"
                },
                "desc": {
                    "description": "备注",
                    "type": "string"
                },
                "house_number": {
                    "description": "房屋栋号(必须)",
                    "type": "string"
                },
                "house_write_off": {
                    "description": "是否完成房屋注销",
                    "type": "boolean"
                },
                "initial_hq_area": {
                    "description": "初始回迁面积(必须)",
                    "type": "number"
                },
                "is_delivery": {
                    "description": "是否交齐楼（必须为1）",
                    "type": "boolean"
                },
                "old_address": {
                    "description": "被拆迁的地址(必须)",
                    "type": "string"
                },
                "peoples": {
                    "description": "被拆迁人(至少一个，可能有多个)",
                    "type": "string"
                },
                "phone_number1": {
                    "description": "手机号码1",
                    "type": "string"
                },
                "phone_number2": {
                    "description": "手机号码2",
                    "type": "string"
                },
                "proprietor": {
                    "description": "证载产权人",
                    "type": "string"
                },
                "registration": {
                    "description": "登记字号",
                    "type": "string"
                },
                "signatory": {
                    "description": "签约人(必须)",
                    "type": "string"
                },
                "social_category": {
                    "description": "社别(必须)",
                    "type": "string"
                },
                "staging_id": {
                    "description": "分期id(必须)",
                    "type": "integer"
                }
            }
        },
        "api.AddDeclarationBody": {
            "type": "object",
            "required": [
                "contract_no"
            ],
            "properties": {
                "contract_no": {
                    "description": "合同号",
                    "type": "string"
                },
                "huxing_id": {
                    "description": "户型id",
                    "type": "integer"
                },
                "time_id": {
                    "description": "现场确认时段id",
                    "type": "integer"
                },
                "trustee": {
                    "description": "受托人",
                    "type": "string"
                },
                "trustee_card_number": {
                    "description": "受托人身份证号码",
                    "type": "string"
                },
                "trustee_phone_number": {
                    "description": "受托人手机号码",
                    "type": "string"
                },
                "trustee_relationship": {
                    "description": "受托人关系",
                    "type": "string"
                }
            }
        },
        "app.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "type": "object"
                },
                "msg": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo swaggerInfo

type s struct{}

func (s *s) ReadDoc() string {
	t, err := template.New("swagger_info").Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, SwaggerInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
